In [8]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr)


[1 2 3 4]


In [9]:
print(np.__version__)

2.4.3


In [10]:
print(type(arr))

<class 'numpy.ndarray'>


In [16]:
arrr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [17]:
print(arrr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
print(arr[0])


[1 2 3 4]


In [3]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70])
ans = arr[:4]
print(ans)


[10 20 30 40]


In [6]:
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40])
ans = arr[::2]
print(ans)

[ 5 15 25 35]


In [11]:
arr = np.array([100, 200, 300, 400, 500])
ans = arr[-1]
print(ans)


[]


In [20]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [21]:
ans = arr[:, 1:3]

print(ans)

[[ 2  3]
 [ 6  7]
 [10 11]]
